name: nf-core-atacseq-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
    ## conda-forge packages
    - conda-forge::r-base=3.4.1
    - conda-forge::r-optparse=1.6.0
    - conda-forge::r-rcolorbrewer=1.1_2
    - conda-forge::r-ggplot2=3.1.0
    - conda-forge::r-reshape2=1.4.3
    - conda-forge::r-scales=1.0.0
    - conda-forge::r-pheatmap=1.0.10
    - conda-forge::r-lattice=0.20_35
    - conda-forge::r-upsetr=1.3.3

    ## bioconda packages
    - bioconda::fastqc=0.11.8
    - bioconda::trim-galore=0.5.0
    - bioconda::bwa=0.7.17
    - bioconda::samtools=1.9
    - bioconda::picard=2.18.26
    - bioconda::bamtools=2.5.1
    - bioconda::pysam=0.15.2
    - bioconda::bedtools=2.27.1
    - bioconda::ucsc-bedgraphtobigwig=377
    - bioconda::macs2=2.1.2
    - bioconda::homer=4.9.1
    - bioconda::ataqv=1.0.0
    - bioconda::subread=1.6.3
    - bioconda::multiqc=1.7
    - bioconda::bioconductor-deseq2=1.20.0
    - bioconda::bioconductor-vsn=3.46.0
