name: nf-core-atacseq-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
    ## conda-forge packages
    - conda-forge::r-base=3.4.1
    - conda-forge::r-optparse=1.6.0
    - conda-forge::r-rcolorbrewer=1.1_2
    - conda-forge::r-ggplot2=3.1.0
    - conda-forge::r-reshape2=1.4.3
    - conda-forge::r-scales=1.0.0
    - conda-forge::r-pheatmap=1.0.10
    - conda-forge::r-lattice=0.20_35
    - conda-forge::r-upsetr=1.3.3

    ## bioconda packages
    - fastqc=0.11.8
    - trim-galore=0.5.0
    - bwa=0.7.17
    - samtools=1.9
    - picard=2.18.26
    - bamtools=2.5.1
    - pysam=0.15.2
    - bedtools=2.27.1
    - ucsc-bedgraphtobigwig=377
    - macs2=2.1.2
    - homer=4.9.1
    - ataqv=1.0.0
    - subread=1.6.3
    - multiqc=1.7
    - bioconda::bioconductor-deseq2=1.20.0
    - bioconda::bioconductor-vsn=3.46.0
